insert into REGION (name) VALUES
     ('England'),
     ('Portugal'),
     ('Spain'),
     ('France'),
     ('Germany'),
     ('Russia'),
     ('Japan'),
     ('Italy'),
     ('Israel'),
     ('Sweden'),
     ('USA'),
     ('China'),
     ('Brasil'),
     ('Equador');
