package backend.bookSharing.repository.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.sql.Timestamp;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * not necessary if we limit amount of sessions for an account to one. Then delete table and change values to user
 *
 * Authentication tokens for users
 */
@Getter
@Entity()
@Table(name = "Token")
@NoArgsConstructor
public class Token {

    @Id
    @Column(name = "token_validation", length = 256)
    private String token;

    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    @Column(name = "created_at", insertable = false)
    private Timestamp createdDate;

    @Setter
    @Column(name = "last_used_at", insertable = false)
    private Timestamp lastUsed;

    /**
     * Should not be necessary, but this does not retrieve generated by default. todo find a way to do it
     * @param token authentication token
     * @param user user to who belongs the token
     */
    public Token(String token, User user) {
        this.token = token;
        this.user = user;
    }

    @Override
    public String toString() {
        return String.format("Token[hash='%s', user='%s' created_date='%s', last_used ='%s']",
                token,
                user.toString(),
                createdDate.toString(),
                lastUsed.toString()
        );
    }

}
