package backend.bookSharing.repository.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.sql.Timestamp;

@Entity()
@Table(name = "Token")
/**
 * not necessary if we limit amount of sessions for an account to one. Then delete table and change values to user
 *
 * Authentication tokens for users
 */
public class Token {

    @Id
    @JoinColumn(name = "token_validation")
    private String token;

    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    private Timestamp created_date;

    private Timestamp last_used;

    public Token() {
    }

    /**
     * Should not be necessary, but this does not retrieve generated by default. todo find a way to do it
     * @param token authentication token
     * @param user user to who belongs the token
     */
    public Token(String token, User user) {
        this.token = token;
        this.user = user;
    }

    @Override
    public String toString() {
        return String.format("Token[hash='%s', user='%s' created_date='%s', last_used ='%s']",
                token,
                user.toString(),
                created_date.toString(),
                last_used.toString()
        );
    }

    public String getToken() {
        return token;
    }

    public User getUser() {
        return user;
    }

    public Timestamp getCreatedDate() {
        return created_date;
    }

    public Timestamp getLastUsed() {
        return last_used;
    }

    public void setLast_used(Timestamp last_used) {
        this.last_used = last_used;
    }
}
