package backend.bookSharing.repository.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.sql.Timestamp;
import lombok.Getter;
import lombok.Setter;

@Entity()
@Table(name = "Token")
/**
 * not necessary if we limit amount of sessions for an account to one. Then delete table and change values to user
 *
 * Authentication tokens for users
 */
public class Token {

    @Id
    @Column(name = "token_validation", length = 256)
    private String token;

    @Getter
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    @Column(name = "created_at", insertable = false)
    private Timestamp created_date;

    @Setter
    @Column(name = "last_used_at", insertable = false)
    private Timestamp last_used;

    public Token() {
    }

    /**
     * Should not be necessary, but this does not retrieve generated by default. todo find a way to do it
     * @param token authentication token
     * @param user user to who belongs the token
     */
    public Token(String token, User user) {
        this.token = token;
        this.user = user;
    }

    @Override
    public String toString() {
        return String.format("Token[hash='%s', user='%s' created_date='%s', last_used ='%s']",
                token,
                user.toString(),
                created_date.toString(),
                last_used.toString()
        );
    }

    public String getToken() {
        return token;
    }

    public Timestamp getCreatedDate() {
        return created_date;
    }

    public Timestamp getLastUsed() {
        return last_used;
    }

}
